/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
<<<<<<< HEAD
<<<<<<< HEAD
 * Generated at: 2019-05-29 06:02:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1559109678771L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1559106344946L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/index.css\" />\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/common.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t/* 메뉴바 클릭 이벤트 */\r\n");
      out.write("\t$(\"#menu_img\").click(function(){\r\n");
      out.write("\t\t$(\"#menubar\").animate({'right':'0px'},300,'linear');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#close\").click(function(){\r\n");
      out.write("\t\t$(\"#menubar\").animate({'right':'-300px'},300,'linear');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<!-- 헤더 -->\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div id=\"header-container\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\">\r\n");
      out.write("\t\t\t\t<img id=\"logo_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\"/>\r\n");
      out.write("\t\t\t\t<span>HelloWorld</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\">\r\n");
      out.write("\t\t\t\t<img id=\"chat_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/chat.png\"/>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<img id=\"menu_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/menu.png\"/>\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 메뉴바 -->\r\n");
      out.write("\t\t<div id=\"menubar\">\r\n");
      out.write("\t\t\t<span id=\"close\">x</span>\r\n");
      out.write("\t\t\t<form action=\"\" \r\n");
      out.write("\t\t\t\t  id=\"loginfrm\"\r\n");
      out.write("\t\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t\t  onsubmit=\"return loginValidate();\">\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t<span class=\"text\">로그인이 필요합니다.</span>\r\n");
      out.write("\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/userid.png\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"memberId\" placeholder=\"   ID\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"login_btn\" type=\"submit\" value=\"로그인\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/key.png\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"password\" placeholder=\"   PASSWORD\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t&nbsp;\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"아이디/비밀번호찾기\"\r\n");
      out.write("\t\t\t\t   class=\"membermenu\"\r\n");
      out.write("\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("'\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"회원가입\"\r\n");
      out.write("\t\t\t\t   class=\"membermenu\"\r\n");
      out.write("\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll'\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 메뉴목록 -->\r\n");
      out.write("\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">문의사항</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;ⓒ  copyright 2019. <strong>HelloWorld</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
=======
 * Generated at: 2019-05-30 06:08:46 UTC
=======
 * Generated at: 2019-05-31 06:16:59 UTC
>>>>>>> refs/remotes/origin/jimin
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1559283412810L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1559196497628L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");

	//쿠키 관련 처리
	Cookie[] cookies = request.getCookies();
	boolean saveIdFlag = false;
	String memberIdSaved = "";
	
	if(cookies != null){
		for(Cookie c: cookies){
			String key = c.getName();
			String value = c.getValue();
			if("saveId".equals(key)){
				saveIdFlag = true;
				memberIdSaved = value;
			}
		}
	}
	if(memberLoggedIn != null){
	System.out.println(memberLoggedIn.getAnswer().replaceAll(" ", "").replaceAll("\\p{Z}", ""));
	}
	System.out.println("멤버로그드인=="+memberLoggedIn);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/common.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t/* 메뉴바 클릭 이벤트 */\r\n");
      out.write("\t$(\"#menu_img\").click(function(){\r\n");
      out.write("\t\t$(\"#menubar\").animate({'right':'0px'},300,'linear');\r\n");
      out.write("\t\t$(\"#menubar\").css(\"display\",\"inline\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#menubar-close\").click(function(){\r\n");
      out.write("\t\t$(\"#menubar\").animate({'right':'-290px'},300, function(){\r\n");
      out.write("\t\t\t$(\"#menubar\").css(\"display\",\"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#chat-close\").click(function(){\r\n");
      out.write("\t\t$(\"#chat-container\").css({'display':'none'});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\t $(\"#chat-container\").draggable();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function chatFunction(){\r\n");
      out.write("\t  var x = document.getElementById(\"chat-container\");\r\n");
      out.write("\t  if (x.style.display === \"none\") {\r\n");
      out.write("\t    x.style.display = \"block\";\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t    x.style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function findMember(){\r\n");
      out.write("\t//아이디, 비밀번호 찾기 팝업 생성\r\n");
      out.write("\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/member/findMember\";\r\n");
      out.write("\tvar title = \"findMember\";\r\n");
      out.write("\tvar spec = \"width=500px, height=750px, left=500px, top=100px\";\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar popup = open(url, title, spec); \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"header-container\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\">\r\n");
      out.write("\t\t\t<img id=\"logo_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\"/>\r\n");
      out.write("\t\t\t<span>HelloWorld</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<img id=\"chat_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/chat.png\" onclick=\"chatFunction();\"/>\r\n");
      out.write("\t\t\t<img id=\"menu_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/menu.png\"/>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 채팅화면 -->\r\n");
      out.write("        <div id=\"chat-container\">\r\n");
      out.write("            <span id=\"chat-title\">1:1 문의하기</span>\r\n");
      out.write("            <span id=\"chat-close\">x</span>\r\n");
      out.write("            <div id=\"msg-container\">\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅dodododd앵웅doddodododod</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"input\">\r\n");
      out.write("                <input type=\"text\"/>\r\n");
      out.write("                <button>전송</button>\r\n");
      out.write("            </div>        \r\n");
      out.write("        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 메뉴바 -->\r\n");
      out.write("\t<div id=\"menubar\">\r\n");
      out.write("\t\t<span id=\"menubar-close\">X</span>\r\n");
      out.write("\t\t<!-- 로그인 메뉴/폼 -->\r\n");
      out.write("\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");
if(memberLoggedIn == null){ 
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" \r\n");
      out.write("\t\t\t\t  id=\"loginfrm\"\r\n");
      out.write("\t\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t\t  >\r\n");
      out.write("\t\t\t\t<span class=\"text\">로그인이 필요합니다.</span>\r\n");
      out.write("\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/userid.png\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"memberId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   id=\"memberId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   placeholder=\"   ID\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.print(saveIdFlag?memberIdSaved:"" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"login_btn\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"loginSubmit();\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"로그인\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/key.png\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   placeholder=\"   PASSWORD\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   id=\"saveId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   ");
      out.print(saveIdFlag?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"saveId\">아이디 저장</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t&nbsp;\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"아이디/비밀번호찾기\"\r\n");
      out.write("\t\t\t\t   class=\"membermenu\"\r\n");
      out.write("\t\t\t\t   onclick=\"findMember();\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"회원가입\"\r\n");
      out.write("\t\t\t\t   class=\"membermenu\"\r\n");
      out.write("\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll'\"/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t");

		}
		else{
		
      out.write("\r\n");
      out.write("\t\t\t<table id='logged-in'>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"profile-div\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"profile-viewer\"\r\n");
      out.write("\t\t\t\t\t \t\t src=\"");
      out.print(request.getContextPath());
      out.write("/upload/member/profile/");
      out.print(memberLoggedIn.getRenamedImgName());
      out.write("\" \r\n");
      out.write("\t\t\t\t\t \t\t width=\"100px\" height=\"100px\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(memberLoggedIn.getMemberName());
      out.write("님! 안녕하세용</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type='button' \r\n");
      out.write("\t\t\t\t\t\t\t   value='My Page'\r\n");
      out.write("\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberMyPage?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("'\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type='button'\r\n");
      out.write("\t\t\t\t\t\t\t   value='LogOut'\r\n");
      out.write("\t\t\t\t\t\t\t   onclick=\"logoutFunction();\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"loginCheck\" id=\"loginCheck\" value=\"0\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 로그인 메뉴/폼 끝 -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\tfunction loginSubmit(){\r\n");
      out.write("\t\t\tif($(\"#memberId\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#password\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar param = {\r\n");
      out.write("\t\t\t\t\tmemberId : $(\"#memberId\").val(),\r\n");
      out.write("\t\t\t\t\tpassword : $(\"#password\").val(),\r\n");
      out.write("\t\t\t\t\tsaveId : $(\"#saveId\").val()\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tconsole.log(\"아이디=\"+memberId);\r\n");
      out.write("\t\t\tconsole.log(\"비번=\"+password);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/member/login\",\r\n");
      out.write("\t\t\t\tdata: param,\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tvar member = data;\r\n");
      out.write("\t\t\t\t\tvar msg = member.msg;\r\n");
      out.write("\t\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\t\tvar memberId = member.memberId;\r\n");
      out.write("\t\t\t\t\t//console.dir(data);\r\n");
      out.write("\t\t\t\t\tif(msg=='로그인성공'){\r\n");
      out.write("\t\t\t\t\t\tvar memberName = member.memberName;\r\n");
      out.write("\t\t\t\t\t\tvar memberProfile = member.renamedImgName;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtml += \"<table id='logged-in'><tr>\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\"<td rowspan='2'><div id='profile-div'>\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\"<img id='profile-viewer'\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\"src='");
      out.print(request.getContextPath());
      out.write("/upload/member/profile/\"+memberProfile+\"'\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\" width='100px' height='100px'/></div></td>\";\r\n");
      out.write("\t\t\t\t\t \t\t \r\n");
      out.write("\t\t\t\t\t\thtml+=\"<td>\"+memberName+\"님! 안녕하세용</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\"<tr><td><input type='button' value='My Page'/>\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\" <input type='button' value='LogOut'\";\r\n");
      out.write("\t\t\t\t\t\thtml+=\"onclick='logoutFunction();'/>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtml+=\"</td></tr></table>\";\r\n");
      out.write("\t\t\t\t\t\t$(\".login-container\").html(html);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\tvar menu = \"<ul><li><a href='");
      out.print(request.getContextPath());
      out.write("'>일정보기</a></li>\";\r\n");
      out.write("\t\t\t\t\t\tmenu+=\"<li><a href='");
      out.print(request.getContextPath());
      out.write("/test'>내글보기</a></li>\";\r\n");
      out.write("\t\t\t\t\t\tmenu+=\"<li><a href='");
      out.print(request.getContextPath());
      out.write("'>찜리스트</a></li>\";\r\n");
      out.write("\t\t\t\t\t\tmenu+=\"<li><a href='");
      out.print(request.getContextPath());
      out.write("'>리뷰쓰기</a></li>\";\r\n");
      out.write("\t\t\t\t\t\tmenu+=\"<li><a href='");
      out.print(request.getContextPath());
      out.write("'>공지사항</a></li>\";\r\n");
      out.write("\t\t\t\t\t\tmenu+=\"<li><a href='");
      out.print(request.getContextPath());
      out.write("'>문의사항</a></li></ul>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#menu\").html(menu);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(a, b, c){\r\n");
      out.write("\t\t\t\t\tconsole.log(a);\r\n");
      out.write("\t\t\t\t\tconsole.log(b);\r\n");
      out.write("\t\t\t\t\tconsole.log(c);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction logoutFunction(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/member/Logout\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 메뉴목록 -->\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t");
if(memberLoggedIn != null) {
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">일정보기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">내글보기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">찜리스트</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">리뷰쓰기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">문의사항</a></li>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">공지사항</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 메뉴바 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section id=\"content\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/index.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/*인덱스 페이지  검색 */\r\n");
      out.write("/*국가 입력 자동완성  */\r\n");
      out.write("ul#autocomplete{\r\n");
      out.write("\tmin-width:171px;\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("\t display: inline-block;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("}\r\n");
      out.write("ul#autocomplete li{\r\n");
      out.write("\tpadding: 0 10px;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("ul#autocomplete li.sel{\r\n");
      out.write("\tbackground: pink;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("/*사용자 입력값 하이라이트처리*/\r\n");
      out.write("span.srchval{color:red;}\r\n");
      out.write("div#destination {\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("}\r\n");
      out.write("/*나라 고르기  */\r\n");
      out.write("span.nation:hover {\r\n");
      out.write("\tcolor: pink;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("/*일정고르기  */\r\n");
      out.write("\r\n");
      out.write("span.days:hover{\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\t} \r\n");
      out.write("h3#days, span.days{\r\n");
      out.write("\tdisplay:none;}\r\n");
      out.write("div#destination{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write(" <h2> HELLO WORLD</h2>\r\n");
      out.write(" <nav class=\"navbar navbar-light bg-light\">\r\n");
      out.write("  <form class=\"form-inline\">\r\n");
      out.write("    <input name=\"srchNation\" id=\"srchNation\" type=\"search\" placeholder=\"나라를 입력해주세요.\"> &nbsp;\r\n");
      out.write("    <button id = \"btn-search\">검색</button>\r\n");
      out.write("   \t\r\n");
      out.write("   \t<ul id=\"autocomplete\">\r\n");
      out.write("   \t\t<li class=\"sel\"></li>\r\n");
      out.write("   \t\t<li></li>\r\n");
      out.write("   \t\t<li></li>\r\n");
      out.write("   \t\t<li></li>\r\n");
      out.write("   \t</ul>\r\n");
      out.write("  </form>\r\n");
      out.write("  <br />\r\n");
      out.write("  <div id=\"destination\">\r\n");
      out.write("  \t<h3 id=\"nation\">어디로 가실건가요? </h3>\r\n");
      out.write("  \t\t<span class=\"nation\" nid=\"일본\" value=\"일본\" >일본</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"nation\" nid=\"중국\" >중국</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"nation\" nid=\"동남아\" >동남아</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"nation\" nid=\"유럽\" >유럽</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"nation\" nid=\"미국\" >미국</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"nation\" nid=\"호주/뉴질랜드\">호주/뉴질랜드</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<br /><br />\r\n");
      out.write("  \t<h3 id=\"days\"> 일정 </h3>\r\n");
      out.write("  \t\t<br />\r\n");
      out.write("  \t\t<span class=\"days\" did=\"1\">1~3일</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"days\" did=\"2\">3~4일</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"days\" did=\"3\">5~9일</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"days\" did=\"4\">10~15일</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t<span class=\"days\" did=\"5\">2주 이상</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t<br />\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<button type=\"button\" class=\"review\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/reviewFrm\"> 리뷰 작성 </a></button>\r\n");
      out.write("<script>\r\n");
      out.write("  //검색창을 클릭하면 나라 고르는 거 나오기\r\n");
      out.write("$(function(){ \r\n");
      out.write("\t$(\"input#srchNation\").focus(function(){\r\n");
      out.write("\t$(\"div#destination\").css(\"transition\",\"3s\").show();\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"span.nation\").click(function(){\r\n");
      out.write("\t\t\tvar srchNation = $(\"#srchNation\");\r\n");
      out.write("\t\t\tvar nid = $(this).attr(\"nid\");\r\n");
      out.write("\t\t\tvar html = $(this).text();\r\n");
      out.write("\t\t\t$(this).css(\"color\", \"pink\");\t\r\n");
      out.write("\t\t\t srchNation.val(html);\r\n");
      out.write("\t\t\tif(nid == undefined) return;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//나라를 클릭한 후에 일정 보여지기\r\n");
      out.write("\t\t\t$(\"h3#days,span.days\").css(\"transition\",\"3s\").show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//일정을 정하면 해당 국가 페이지로 이동\r\n");
      out.write("\t\t\t\t$(\"span.days\").click(function(){\r\n");
      out.write("\t\t\t\tvar did = $(this).attr(\"did\");\r\n");
      out.write("\t\t\t\t$(this).css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\thtml += \", \" + $(this).text();\r\n");
      out.write("\t\t\t\t srchNation.val(html);\t\t\t\t\r\n");
      out.write("\t\t\t\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/nationToCity?nid=' +nid;\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("$(function(){\t\r\n");
      out.write("\t$(\"input#srchNation\").keyup(function(key){\r\n");
      out.write("\t\tvar srchNation = $(\"#srchNation\").val();\r\n");
      out.write("\t\tconsole.log(srchNation);\r\n");
      out.write("\t\t\tif(key.keyCode==13){\r\n");
      out.write("\t\t\t\t//if(srchNation.length ==0) return;\r\n");
      out.write("\t\t\t location.href='");
      out.print(request.getContextPath());
      out.write("/nationToCity?nid=' +$(this).val();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("//자동 완성 기능\r\n");
      out.write(" $(function(){\r\n");
      out.write("    $(\"#srchNation\").keyup(function(e){\r\n");
      out.write("        //눌린 키가 뭔지 알기 위해서 e라고 이벤트 객체를 받겠음\r\n");
      out.write("        var srchNation = $(\"#srchNation\").val();\r\n");
      out.write("        //사용자 입력값이 공백인 경우, ajax 요청하지 않는다.\r\n");
      out.write("        if(srchNation.length == 0)\r\n");
      out.write("            return;\r\n");
      out.write("        \r\n");
      out.write("        var $sel = $(\".sel\");\r\n");
      out.write("        var $li = $(\"#autocomplete li\");\r\n");
      out.write("        //사용자 입력값이 ArrowUp인 경우 (화살표 키 위로)\r\n");
      out.write("        if(e.key == 'ArrowUp'){          \r\n");
      out.write("            if($sel.length == 0){\r\n");
      out.write("                //처리 없음\r\n");
      out.write("            }\r\n");
      out.write("            //현재 선택된 요소가 $li 첫 번째 요소인 경우\r\n");
      out.write("            else if($sel.is($li.first())){\r\n");
      out.write("                $sel.removeClass(\"sel\");\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("                $sel.removeClass(\"sel\").prev().addClass(\"sel\");\r\n");
      out.write("            }} \r\n");
      out.write("        //사용자 입력값이 ArrowDown인 경우 (화살표 키 밑으로)\r\n");
      out.write("        else if(e.key == 'ArrowDown'){\r\n");
      out.write("            if($sel.length == 0){\r\n");
      out.write("                $li.first().addClass(\"sel\");\r\n");
      out.write("            }\r\n");
      out.write("            //현재 선택된 요소가 $li 마지막 요소인 경우\r\n");
      out.write("            else if($sel.is($li.last())){\r\n");
      out.write("                //처리 코드 없음\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("                $sel.removeClass(\"sel\")\r\n");
      out.write("                    .next()\r\n");
      out.write("                    .addClass(\"sel\");\r\n");
      out.write("            }}\r\n");
      out.write("        //사용자 입력값이 Enter인 경우\r\n");
      out.write("        else if(e.key == 'Enter'){\r\n");
      out.write("        \t//현재 선택값을 input 태그에 입력\r\n");
      out.write("        \t$(this).css('transition','300');\r\n");
      out.write("            $(this).val($sel.text());\r\n");
      out.write("        \t//검색어 목록을 감추고, li태그 삭제\r\n");
      out.write("        \t$(\"#autocomplete\").hide().children().remove();\r\n");
      out.write("        \t$(this).css('transition','200');\r\n");
      out.write("            $(function(){\r\n");
      out.write("                location.href= '");
      out.print(request.getContextPath());
      out.write("/main/nationToCity?nid='+$(this).text();\r\n");
      out.write("                })\r\n");
      out.write("        \t//선택된 값을 가지고, 다음 서비스 제공\r\n");
      out.write("        //\talert($(this).val()+\"\");\r\n");
      out.write("        }\r\n");
      out.write("        //그외 (ajax 요청 보낼 것. 위에 세 가지는 ajax 요청 보낼 필요 X)\r\n");
      out.write("        else{\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"");
      out.print(request.getContextPath());
      out.write("/main/search\",\r\n");
      out.write("                data: \"srchNation=\"+srchNation, //파라미터 직렬화. data속성으로 파라미터 전송.\r\n");
      out.write("                success: function(data){\r\n");
      out.write("                    console.log(data);\r\n");
      out.write("                    //$(\"#search\").text(data);\r\n");
      out.write("                    \r\n");
      out.write("                    //넘어온 csv 데이타가 공백인 경우\r\n");
      out.write("                    if(data.trim().length == 0){\r\n");
      out.write("                        $(\"#autocomplete\").hide();\r\n");
      out.write("                    }\r\n");
      out.write("                    else{\r\n");
      out.write("                        var nameArr = data.split(\" \");\r\n");
      out.write("                        var html = \"\";\r\n");
      out.write("                        \r\n");
      out.write("                        for(var i=0; i<nameArr.length; i++){\r\n");
      out.write("                            html += \"<li>\"+nameArr[i].replace(srchNation, \"<span class='srchval'>\"+srchNation+\"</span>\")+\"</li>\";\r\n");
      out.write("                        $(\"#autocomplete\").html(html).fadeIn(30);\r\n");
      out.write("                        }     }\r\n");
      out.write("                    }\r\n");
      out.write("                    })\r\n");
      out.write("                        //enter키 누르면 다음페이지로 넘어가기\r\n");
      out.write("                        $(\"#autocomplete\").keyup(function(e){\r\n");
      out.write("                        \tif(e.key==13)\r\n");
      out.write("                        \tlocation.href='");
      out.print(request.getContextPath());
      out.write("/nationToCity?nid='+searchNation;\r\n");
      out.write("                        \t\t\t/* +$(this).text(); */\t\r\n");
      out.write("                        })\r\n");
      out.write("            }; \r\n");
      out.write("    //end of ajax\r\n");
      out.write("        });\r\n");
      out.write("   //end of $(\"#srchName\").keyup\r\n");
      out.write("    \r\n");
      out.write("    \t//클릭이벤트가 일어난 li태그의 text를 input 태그에 입력\r\n");
      out.write("    $(\"#autocomplete\").on(\"click\",\"li\",function(){\r\n");
      out.write("    \t$(\"#srchName\").val($(this).text());\r\n");
      out.write("    \t$(\"#autocomplete\").hide().children().remove();\r\n");
      out.write("    \tlocation.href='");
      out.print(request.getContextPath());
      out.write("/nationToCity?nid='+$(this).text();\t\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#autocomplete\").on(\"mouseover\",\"li\",function(){\r\n");
      out.write("    \t$(this).siblings().removeClass(\"sel\");\r\n");
      out.write("    \t$(this).addClass(\"sel\");\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#autocomplete\").on(\"mouseout\",\"li\",function(){\r\n");
      out.write("    \t$(this).removeClass(\"sel\");\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;ⓒ  copyright 2019. <strong>HelloWorld</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
>>>>>>> refs/remotes/origin/jimin
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
