/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-05-29 05:45:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("img#profile-viewer{\r\n");
      out.write("\tborder: 1px solid rgba(0,0,0,0);\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("\tborder : none;\r\n");
      out.write("\tborder-bottom: 2px solid;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section id=\"enroll-container\">\r\n");
      out.write("<h1>Join Us,</h1>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnrollEnd\"\r\n");
      out.write("\t  name=\"memberEnrollFrm\" \r\n");
      out.write("\t  method=\"post\"\r\n");
      out.write("\t  enctype=\"multipart/form-data\"\r\n");
      out.write("\t  onsubmit=\"return submitInvalid();\">\r\n");
      out.write("<table id=\"memberEnrollTable\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td rowspan=\"10\">\r\n");
      out.write("\t\t\t<div id=\"profile-div\">\r\n");
      out.write("\t\t\t\t<img id=\"profile-viewer\"\r\n");
      out.write("\t\t\t\t\t src=\"");
      out.print(request.getContextPath());
      out.write("/images/profilebasic.png\" \r\n");
      out.write("\t\t\t\t\t width=\"200px\" height=\"200px\"\r\n");
      out.write("\t\t\t\t\t />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"file\" \r\n");
      out.write("\t\t\t\t   name=\"profile\" \r\n");
      out.write("\t\t\t\t   id=\"profile\"\r\n");
      out.write("\t\t\t\t   style=\"display:none\"\r\n");
      out.write("\t\t\t\t   onchange=\"loadProfile(this);\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<th>아이디</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t   name=\"memberId\"\r\n");
      out.write("\t\t\t\t   id=\"memberId\" \r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t\t<span id=\"checkIdDuplicate\"></span>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"isValid\" value=\"0\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>이름</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t   name=\"memberName\"\r\n");
      out.write("\t\t\t\t   id=\"memberName\"\r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>비밀번호</th>\r\n");
      out.write("\t\t<td><input type=\"password\" \r\n");
      out.write("\t\t\t\t   name=\"password\"\r\n");
      out.write("\t\t\t\t   id=\"password\" \r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>비밀번호 확인</th>\r\n");
      out.write("\t\t<td><input type=\"password\" \r\n");
      out.write("\t\t\t\t   id=\"passwordCheck\"\r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t\t<span id=\"passwordCheck-span\"></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>질문</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<select name=\"question\" \r\n");
      out.write("\t\t\t\t    id=\"question\"\r\n");
      out.write("\t\t\t\t    required>\r\n");
      out.write("\t\t\t\t<option value=\"\">비밀번호 찾기 질문</option>\r\n");
      out.write("\t\t\t\t<option value=\"나의 고향은?\">나의 고향은?</option>\r\n");
      out.write("\t            <option value=\"보물 1호는?\">보물 1호는?</option>\r\n");
      out.write("\t            <option value=\"어머니의 성함은?\">어머니의 성함은?</option>\r\n");
      out.write("\t            <option value=\"나의 가장 친한 친구는?\">나의 가장 친한 친구는?</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>답</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t   id=\"answer\"\r\n");
      out.write("\t\t\t\t   name=\"answer\"\r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>성별</th>\t\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"radio\" \r\n");
      out.write("\t\t\t\t   name=\"gender\"\r\n");
      out.write("\t\t\t\t   id=\"genderF\" \r\n");
      out.write("\t\t\t\t   value=\"F\"\r\n");
      out.write("\t\t\t\t   checked/>\r\n");
      out.write("\t\t\t<label for=\"genderF\">여</label>\r\n");
      out.write("\t\t\t<input type=\"radio\" \r\n");
      out.write("\t\t\t\t   name=\"gender\"\r\n");
      out.write("\t\t\t\t   id=\"genderM\" \r\n");
      out.write("\t\t\t\t   value=\"M\"/>\r\n");
      out.write("\t\t\t<label for=\"genderF\">남</label>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>생년월일</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"date\"\r\n");
      out.write("\t\t\t\t   name=\"birth\" \r\n");
      out.write("\t\t\t\t   id=\"birth\"\r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>전화번호</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"tel\"\r\n");
      out.write("\t\t\t\t   name=\"tel\"\r\n");
      out.write("\t\t\t\t   id=\"tel\"\r\n");
      out.write("\t\t\t\t   required/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>관심사</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t   name=\"interest\" \r\n");
      out.write("\t\t\t\t   id=\"interest0\"\r\n");
      out.write("\t\t\t\t   value=\"맛집\"/>\r\n");
      out.write("\t\t\t<label for=\"interest0\">맛집</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t   name=\"interest\" \r\n");
      out.write("\t\t\t\t   id=\"interest1\"\r\n");
      out.write("\t\t\t\t   value=\"관광\"/>\r\n");
      out.write("\t\t\t<label for=\"interest1\">관광</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t   name=\"interest\" \r\n");
      out.write("\t\t\t\t   id=\"interest2\"\r\n");
      out.write("\t\t\t\t   value=\"휴양\"/>\r\n");
      out.write("\t\t\t<label for=\"interest2\">휴양</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t   name=\"interest\" \r\n");
      out.write("\t\t\t\t   id=\"interest3\"\r\n");
      out.write("\t\t\t\t   value=\"레저\"/>\r\n");
      out.write("\t\t\t<label for=\"interest3\">레저</label>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"가입하기\" />\r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"초기화\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#profile-viewer\").click(function(){\r\n");
      out.write("\t\t$(\"#profile\").click();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loadProfile(f){\r\n");
      out.write("\tconsole.log(f.files);\r\n");
      out.write("\t\r\n");
      out.write("\tif(f.files && f.files[0]){\r\n");
      out.write("\t\tvar reader = new FileReader();\r\n");
      out.write("\t\treader.readAsDataURL(f.files[0]);\r\n");
      out.write("\t\treader.onload = function(){\r\n");
      out.write("\t\t\t$(\"#profile-viewer\").attr(\"src\", reader.result);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submitInvalid(){\r\n");
      out.write("\tvar file = $(\"#profile\").val();\r\n");
      out.write("\tif(file==\"\"){\r\n");
      out.write("\t\t$(\"#profile\").remove();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//유효성 검사 시작\r\n");
      out.write("\t//1.아이디\r\n");
      out.write("\tvar regExp1 = /^[a-z\\d]{4,12}$/;\r\n");
      out.write("    if(!regExpTest(regExp1, \"memberId\", \"사용자 아이디가 부적합합니다.\")){\r\n");
      out.write("         return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //2.아이디 중복 검사\r\n");
      out.write("\tvar isValid = $(\"#isValid\").val();\r\n");
      out.write("\tif(isValid == \"0\"){\r\n");
      out.write("\t\talert(\"아이디 중복 검사를 해 주세요.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//3.비밀번호 검사\r\n");
      out.write("    //숫자/문자/특수문자 포함 형태의 8~15자리 이내의 암호 정규식 \r\n");
      out.write("    var regExp2 = /^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g;\r\n");
      out.write("    //전체길이검사 /(?=^.{8,15}$)/\r\n");
      out.write("    //숫자하나 반드시 포함 /(?=.*\\d)/ 또는  (?=\\d)\r\n");
      out.write("    //영문자 반드시 포함 /(?=.*[a-zA-Z])/\r\n");
      out.write("    //특수문자 반드시 포함  /(?=.*[^a-zA-Z0-9])/\r\n");
      out.write("    //앞뒤에 ^.* .*$를 반드시 작성해야 한다.\r\n");
      out.write("    if(!regExpTest(regExp2, \"password\", \"비밀번호는 8~15자리 숫자/문자/특수문자를 포함해야 합니다.\")){\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("  \t//4.이름 검사 : 한글2글자 이상만 허용. \r\n");
      out.write("    var regExp3 = /^[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]{2,}$/;\r\n");
      out.write("    if(!regExpTest(regExp3, \"memberName\", \"이름을 정확히 입력해 주세요.\")){\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  \t//비밀번호일치여부 검사\r\n");
      out.write("    var pwd = document.getElementById(\"password\");\r\n");
      out.write("    var pwdcheck = document.getElementById(\"passwordCheck\");\r\n");
      out.write("    if(pwd.value != pwdcheck.value){\r\n");
      out.write("    \talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("    \tpwd.select();\r\n");
      out.write("    \treturn false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //전화번호 검사\r\n");
      out.write("    var regExp4 = /^01[0-9]{9}$/;\r\n");
      out.write("    if(!regExpTest(regExp4, \"tel\", \"전화번호를 정확히 입력해 주세요.\")){\r\n");
      out.write("    \treturn false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    return true;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//유효성 검사용 알림창 띄우는 함수\r\n");
      out.write("function regExpTest(regExp, id, msg){\r\n");
      out.write("    if(regExp.test(document.querySelector(\"#\"+id).value)){\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("    alert(msg);\r\n");
      out.write("    return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//아이디 유효성 검사 충족 못 하면 바로 빨간 밑줄\r\n");
      out.write("//아이디 유효성 검사 통과하면 중복 검사 버튼 생성\r\n");
      out.write("$(\"#memberId\").keyup(function(){\r\n");
      out.write("\t$(\"#isValid\").val(\"0\");\r\n");
      out.write("    var regExp = /^[a-z\\d]{4,12}$/;\r\n");
      out.write("    if(!regExp.test(document.querySelector(\"#memberId\").value)){\r\n");
      out.write("        $(\"#memberId\").css(\"border-bottom\", \"2px dashed red\");\r\n");
      out.write("        $(\"#checkIdDuplicate\").html(\"\");\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("        $(\"#memberId\").css(\"border-bottom\", \"2px solid\");\r\n");
      out.write("        $(\"#checkIdDuplicate\").html(\"<input onclick='checkIdDuplicate();' id='checkIdDuplicate-button' type='button' value='중복 검사' />\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//비밀번호 유효성 검사 충족 못 하면 바로 빨간 밑줄\r\n");
      out.write("//숫자/문자/특수문자 포함 형태의 8~15자리 이내의 암호 정규식 \r\n");
      out.write("$(\"#password\").keyup(function(){\r\n");
      out.write("\tvar regExp = /^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g;\r\n");
      out.write("\tif(!regExp.test(document.querySelector(\"#password\").value)){\r\n");
      out.write("\t    $(\"#password\").css(\"border-bottom\", \"2px dashed red\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t    $(\"#password\").css(\"border-bottom\", \"2px solid black\");\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//비밀번호 확인 틀리면 바로 빨간 밑줄\r\n");
      out.write("$(\"#passwordCheck\").keyup(function(){\r\n");
      out.write("    var pwd = document.getElementById(\"password\");\r\n");
      out.write("    var pwdcheck = document.getElementById(\"passwordCheck\");\r\n");
      out.write("\r\n");
      out.write("    if(pwd.value == pwdcheck.value){\r\n");
      out.write("        $(\"#passwordCheck-span\").text(\"O\").css(\"color\", \"black\");\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("        $(\"#passwordCheck-span\").text(\"X\").css(\"color\", \"red\").css(\"font-weight\", \"bold\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("$(\"#password\").keyup(function(){\r\n");
      out.write("    var pwd = document.getElementById(\"password\");\r\n");
      out.write("    var pwdcheck = document.getElementById(\"passwordCheck\");\r\n");
      out.write("\r\n");
      out.write("    if(pwd.value == pwdcheck.value){\r\n");
      out.write("        $(\"#passwordCheck-span\").text(\"O\").css(\"color\", \"black\");\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("        $(\"#passwordCheck-span\").text(\"X\").css(\"color\", \"red\").css(\"font-weight\", \"bold\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//전화번호 11자리 아니면 바로 빨간 밑줄\r\n");
      out.write("$(\"#tel\").keyup(function(){\r\n");
      out.write("    var regExp = /^01[0-9]{9}$/;\r\n");
      out.write("    if(!regExp.test(document.querySelector(\"#tel\").value)){\r\n");
      out.write("        $(\"#tel\").css(\"border-bottom\", \"2px dashed red\");\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("        $(\"#tel\").css(\"border-bottom\", \"2px solid\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function checkIdDuplicate(){\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\tmemberId : $(\"#memberId\").val()\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/member/checkIdDuplicate\",\r\n");
      out.write("\t\tdata: param,\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tif(data==1){\r\n");
      out.write("\t\t\t\t//아이디 사용 가능\r\n");
      out.write("\t\t\t\t$(\"#isValid\").val(\"1\");\r\n");
      out.write("\t\t\t\t$(\"#checkIdDuplicate\").text(\"사용 가능\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t//아이디 이미 존재\r\n");
      out.write("\t\t\t\t$(\"#isValid\").val(\"0\");\r\n");
      out.write("\t\t\t\t$(\"#checkIdDuplicate\").text(\"이미 존재하는 아이디입니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax 처리 실패ㅠ~!~!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
