/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-03 04:10:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class updatePassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1559533144079L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1559402842000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	String visit = (String)request.getAttribute("visit");	

	//쿠키 관련 처리
	Cookie[] cookies = request.getCookies();
	boolean saveIdFlag = false;
	String memberIdSaved = "";
	
	if(cookies != null){
		for(Cookie c: cookies){
			String key = c.getName();
			String value = c.getValue();
			if("saveId".equals(key)){
				saveIdFlag = true;
				memberIdSaved = value;
			}
		}
	}
	if(memberLoggedIn != null){
	System.out.println(memberLoggedIn.getAnswer().replaceAll(" ", "").replaceAll("\\p{Z}", ""));
	}
	System.out.println("멤버로그드인=="+memberLoggedIn);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/common.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t");

	if(visit!=null && "first".equals(visit)){
	
      out.write("\r\n");
      out.write("\t\t$(\"#menubar\").css(\"right\",\"0px\");\r\n");
      out.write("\t\t$(\"#menubar\").css(\"display\",\"inline\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

		visit = "none";
	}
	
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* 메뉴바 클릭 이벤트 */\r\n");
      out.write("\t$(\"#menu_img\").click(function(){\r\n");
      out.write("\t\t$(\"#menubar\").animate({'right':'0px'},300,'linear');\r\n");
      out.write("\t\t$(\"#menubar\").css(\"display\",\"inline\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#menubar-close\").click(function(){\r\n");
      out.write("\t\t$(\"#menubar\").animate({'right':'-290px'},300, function(){\r\n");
      out.write("\t\t\t$(\"#menubar\").css(\"display\",\"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#chat-close\").click(function(){\r\n");
      out.write("\t\t$(\"#chat-container\").css({'display':'none'});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\t $(\"#chat-container\").draggable();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function chatFunction(){\r\n");
      out.write("\t  var x = document.getElementById(\"chat-container\");\r\n");
      out.write("\t  if (x.style.display === \"none\") {\r\n");
      out.write("\t    x.style.display = \"block\";\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t    x.style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function findMember(){\r\n");
      out.write("\t//아이디, 비밀번호 찾기 팝업 생성\r\n");
      out.write("\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/member/findMember\";\r\n");
      out.write("\tvar title = \"findMember\";\r\n");
      out.write("\tvar spec = \"width=500px, height=750px, left=500px, top=100px\";\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar popup = open(url, title, spec); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"header-container\" class=\"header\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\">\r\n");
      out.write("\t\t\t<img id=\"logo_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\"/>\r\n");
      out.write("\t\t\t<span>HelloWorld</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<img id=\"chat_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/chat.png\" onclick=\"chatFunction();\"/>\r\n");
      out.write("\t\t\t<img id=\"menu_img\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/menu.png\"/>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 채팅화면 -->\r\n");
      out.write("        <div id=\"chat-container\">\r\n");
      out.write("            <span id=\"chat-title\">1:1 문의하기</span>\r\n");
      out.write("            <span id=\"chat-close\">x</span>\r\n");
      out.write("            <div id=\"msg-container\">\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅dodododd앵웅doddodododod</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("                <ul class=\"list-group list-group-flush\">웅앵웅</ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"input\">\r\n");
      out.write("                <input type=\"text\"/>\r\n");
      out.write("                <button>전송</button>\r\n");
      out.write("            </div>        \r\n");
      out.write("        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 메뉴바 -->\r\n");
      out.write("\t<div id=\"menubar\">\r\n");
      out.write("\t\t<span id=\"menubar-close\">X</span>\r\n");
      out.write("\t\t<!-- 로그인 메뉴/폼 -->\r\n");
      out.write("\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");
if(memberLoggedIn == null){ 
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" \r\n");
      out.write("\t\t\t\t  id=\"loginfrm\"\r\n");
      out.write("\t\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t\t  onsubmit=\"loginSubmit();\"\r\n");
      out.write("\t\t\t\t  >\r\n");
      out.write("\t\t\t\t<span class=\"text\">로그인이 필요합니다.</span>\r\n");
      out.write("\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/userid.png\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"memberId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   id=\"memberId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   placeholder=\"   ID\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.print(saveIdFlag?memberIdSaved:"" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"login_btn\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   type=\"submit\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"로그인\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/key.png\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   placeholder=\"   PASSWORD\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   id=\"saveId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   ");
      out.print(saveIdFlag?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"saveId\">아이디 저장</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t&nbsp;\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"아이디/비밀번호찾기\"\r\n");
      out.write("\t\t\t\t   class=\"membermenu\"\r\n");
      out.write("\t\t\t\t   onclick=\"findMember();\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"회원가입\"\r\n");
      out.write("\t\t\t\t   class=\"membermenu\"\r\n");
      out.write("\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll'\"/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t");

		}
		else{
		
      out.write("\r\n");
      out.write("\t\t\t<table id='logged-in'>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"profile-div\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"profile-viewer_\"\r\n");
      out.write("\t\t\t\t\t \t\t src=\"");
      out.print(request.getContextPath());
      out.write("/upload/member/profile/");
      out.print(memberLoggedIn.getRenamedImgName());
      out.write("\" \r\n");
      out.write("\t\t\t\t\t \t\t width=\"120px\" height=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(memberLoggedIn.getMemberName());
      out.write("님!<br> 안녕하세용</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type='button' \r\n");
      out.write("\t\t\t\t\t\t\t   value='My Page'\r\n");
      out.write("\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberMyPage?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("'\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type='button'\r\n");
      out.write("\t\t\t\t\t\t\t   value='LogOut'\r\n");
      out.write("\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/Logout'\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"loginCheck\" id=\"loginCheck\" value=\"0\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 로그인 메뉴/폼 끝 -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tfunction loginSubmit(){\r\n");
      out.write("\t\t\tif($(\"#memberId\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#password\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 메뉴목록 -->\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t");
if(memberLoggedIn != null) {
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">일정보기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">내글보기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">찜리스트</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">리뷰쓰기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">문의사항</a></li>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("\">공지사항</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 메뉴바 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section id=\"content\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");

    String memberId = (String)request.getAttribute("memberId");

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/updatePassword.css\" />\r\n");
      out.write("\r\n");
      out.write("<title>비밀번호 변경</title>\r\n");
      out.write("\r\n");
      out.write("<div id=\"updatePassword-container\">\r\n");
      out.write("<br /><br /><br />\r\n");
      out.write("    <h1>비밀번호 변경</h1>\r\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/member/updatePasswordEnd\"\r\n");
      out.write("          id=\"updatePasswordFrm\"\r\n");
      out.write("          name=\"updatePasswordFrm\"\r\n");
      out.write("          method=\"post\"\r\n");
      out.write("          onsubmit=\"return submitInvalid();\">\r\n");
      out.write("        <input type=\"hidden\" name=\"memberId\" value=\"");
      out.print(memberId);
      out.write("\"/>\r\n");
      out.write("        \r\n");
      out.write("        <label for=\"passwordOld\">현재 비밀번호</label>\r\n");
      out.write("        <input type=\"password\"\r\n");
      out.write("               id=\"passwordOld\" name=\"passwordOld\"\r\n");
      out.write("               required/>\r\n");
      out.write("        <br />\r\n");
      out.write("        <label for=\"passwordNew\">새 비밀번호</label>\r\n");
      out.write("        <input type=\"password\"\r\n");
      out.write("               id=\"passwordNew\" name=\"passwordNew\"\r\n");
      out.write("               required/>\r\n");
      out.write("        <br />\r\n");
      out.write("        <label for=\"passwordCheck\">비밀번호 확인</label>\r\n");
      out.write("        <input type=\"password\"\r\n");
      out.write("               id=\"passwordCheck\"\r\n");
      out.write("               required/>\r\n");
      out.write("        <span id=\"passwordCheck-span\"></span>\r\n");
      out.write("        <br />\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/cancel.png\"\r\n");
      out.write("             onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberMyPage?memberId=");
      out.print(memberId);
      out.write("'\"\r\n");
      out.write("             />\r\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/ok.png\"\r\n");
      out.write("             onclick=\"submitFrm();\"\r\n");
      out.write("             />\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function submitInvalid(){\r\n");
      out.write("    //비밀번호 검사\r\n");
      out.write("   //숫자/문자/특수문자 포함 형태의 8~15자리 이내의 암호 정규식\r\n");
      out.write("   var regExp = /^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g;\r\n");
      out.write("   if(!regExpTest(regExp, \"passwordNew\", \"비밀번호는 8~15자리 숫자/문자/특수문자를 포함해야 합니다.\")){\r\n");
      out.write("       return false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submitFrm(){\r\n");
      out.write("\t$(\"updatePasswordFrm\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//유효성 검사용 알림창 띄우는 함수\r\n");
      out.write("function regExpTest(regExp, id, msg){\r\n");
      out.write("   if(regExp.test(document.querySelector(\"#\"+id).value)){\r\n");
      out.write("       return true;\r\n");
      out.write("   }\r\n");
      out.write("   alert(msg);\r\n");
      out.write("   return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//비밀번호 유효성 검사 충족 못 하면 바로 빨간 밑줄\r\n");
      out.write("//숫자/문자/특수문자 포함 형태의 8~15자리 이내의 암호 정규식\r\n");
      out.write("$(\"#passwordNew\").keyup(function(){\r\n");
      out.write("    var regExp = /^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g;\r\n");
      out.write("    if(!regExp.test(document.getElementById(\"passwordNew\").value)){\r\n");
      out.write("        $(\"#passwordNew\").css(\"border-bottom\", \"2px dashed red\");\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("        $(\"#passwordNew\").css(\"border-bottom\", \"2px solid black\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//비밀번호 확인 틀리면 바로 빨간 밑줄\r\n");
      out.write("$(\"#passwordCheck\").keyup(function(){\r\n");
      out.write("   var pwd = document.getElementById(\"passwordNew\");\r\n");
      out.write("   var pwdcheck = document.getElementById(\"passwordCheck\");\r\n");
      out.write("\r\n");
      out.write("   if(pwd.value == pwdcheck.value){\r\n");
      out.write("       $(\"#passwordCheck-span\").text(\"O\").css(\"color\", \"black\");\r\n");
      out.write("       return true;\r\n");
      out.write("   }\r\n");
      out.write("   else{\r\n");
      out.write("       $(\"#passwordCheck-span\").text(\"X\").css(\"color\", \"red\").css(\"font-weight\", \"bold\");\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("$(\"#passwordNew\").keyup(function(){\r\n");
      out.write("   var pwd = document.getElementById(\"passwordNew\");\r\n");
      out.write("   var pwdcheck = document.getElementById(\"passwordCheck\");\r\n");
      out.write("\r\n");
      out.write("   if(pwd.value == pwdcheck.value){\r\n");
      out.write("       $(\"#passwordCheck-span\").text(\"O\").css(\"color\", \"black\");\r\n");
      out.write("       return true;\r\n");
      out.write("   }\r\n");
      out.write("   else{\r\n");
      out.write("       $(\"#passwordCheck-span\").text(\"X\").css(\"color\", \"red\").css(\"font-weight\", \"bold\");\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;ⓒ  copyright 2019. <strong>HelloWorld</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
